### ISSUE TITLE
HIP build failing with hiprtc related error. #23 (CONT-D)

### ISSUE THREAD

**Issue by jdgh000** [ROCm/clr#39] opened 2023-12-13 23:50 UTC
THis is continued from following which closed without confirmation: HIP build failing with hiprtc related error. #23
First I want to ask why are you closing without even confirming with me that build works? Build is still failing, please do not close because I cant re-open!!!

Your last post here absolutely makes no sense:
the idea here is, there are two repo you need to build HIP on AMD platforms (there are several but for our purpose we can ignore them).
As I said clr was not building due to hiprtc related error. Are you saying checkout hip and clr, which one to build first?
IF i build clr, it fails with same reason. 
```
It starts with which version of ROCm you have installed.
you can figure it out by doing a cat /opt/rocm/.info/version-dev

You will get a number 5.6 or 5.7

After that you need to checkout the repo
https://github.com/ROCm-Developer-Tools/clr
https://github.com/ROCm-Developer-Tools/hip
to rocm-5.n whatever your ROCm version was installed and then try to build it.

Here clr and hip version needs to match




```

**Comment by schung-amd** [comment] 2024-09-18 17:36
Hi @jdgh000, sorry for the wait and that this was closed on you. Are you still experiencing this issue?

**Comment by schung-amd** [comment] 2024-09-25 18:32
I can't reproduce this on ROCm 6.2. Not sure if this was a versioning issue as noted, or if something has changed since this issue was current. I was able to build `clr` (and HIP as a prerequisite) following the instructions at https://rocm.docs.amd.com/projects/HIP/en/develop/install/build.html followed by the instructions to build `clr` in https://github.com/ROCm/clr/blob/amd-staging/README.md.

To clarify what the post you quoted is saying, these two repos have different branches corresponding to different versions of ROCm, so you have to make sure to pull the correct branch for your version of ROCm, as noted in the HIP guide. If you pull branches whose versions do not match, this can cause issues like those you have seen.

The HIP guide involves pulling both the HIP and `clr` repos and building HIP. Afterward, follow the `clr` guide, which says at one point

```
For HIP:
cmake .. -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=$HIP_COMMON_DIR

HIP_COMMON_DIR points to [HIP](https://github.com/ROCm/HIP)
```

Replace `HIP_COMMON_DIR` here with the location that HIP was built to, and you should be able to build `clr`. 

The `clr` and HIP guides also point to guidance on building `hip-tests` to test the functionality of your installation. Note that the `hip-tests` repo also has branches corresponding to ROCm version, and if you pull the wrong branch you will likely see failing tests.

I'll close the other issue and leave this one open for now, in case you have any further questions about building HIP and `clr`. Also, in the future, if we close an issue and you feel it is unresolved, comment on the issue and we can reopen it. You are free to resubmit the issue (as you did here) if you prefer, but it is more convenient to have all the information in one place.

**Comment by schung-amd** [comment] 2024-10-04 14:07
Closing this here as well for now. As mentioned, feel free to comment on this issue if you'd like it reopened, or you can submit a new issue.

**Closed** 2024-10-04 14:07 UTC
Labels: Under Investigation

**Comment by jdgh000** [comment] 2024-11-01 22:06
please re-open this issue, i never asked it is ok to close, why would close?
The information provided you in above post is useless, i already read through.
If you can not reproduce under ROCM6.2, paste the whole log which I see you did not do so i can compare. 
AFAIK, it is so easily reproducible:

sudo cmake .. -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=../HIP
-- The C compiler identification is GNU 11.5.0
-- The CXX compiler identification is GNU 11.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIPCC Binary Directory: /opt/rocm/bin
-- HIP Common Directory: ../HIP
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found AMD_OPENCL: /root/rocm/ROCm-6.2/clr/opencl/khronos/headers/opencl2.2/CL
CMake Error at rocclr/cmake/ROCclrLC.cmake:37 (file):
  file STRINGS file
  "/root/rocm/ROCm-6.2/clr/rocclr/../HIP/VERSION"
  cannot be read.
Call Stack (most recent call first):
  rocclr/cmake/ROCclr.cmake:139 (include)
  rocclr/CMakeLists.txt:30 (include)


-- Found NUMA: /usr/lib64/libnuma.so
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- HIPCC_BIN_DIR found at /opt/rocm/bin
-- HIP_COMMON_DIR found at ../HIP
-- HIPNV_DIR found at
-- Found Perl: /bin/perl (found version "5.32.1")
CMake Error at hipamd/CMakeLists.txt:88 (file):
  file STRINGS file
  "/root/rocm/ROCm-6.2/clr/hipamd/../HIP/VERSION"
  cannot be read.


-- Found Git: /bin/git (found version "2.43.5")
-- Using CPACK_DEBIAN_PACKAGE_RELEASE local
-- CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- HIP Platform: amd
-- HIP Runtime: rocclr
-- HIP Compiler: clang
-- ROCM Installation path(ROCM_PATH): /opt/rocm
-- HIP will be installed in: /opt/rocm
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib64/libtinfo.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Found zstd: /usr/lib64/libzstd.so
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.13")
'sh' '-c' '/root/rocm/ROCm-6.2/clr/hipamd/src/hip_embed_pch.sh ../HIP/include /root/rocm/ROCm-6.2/clr/build/hipamd/include /root/rocm/ROCm-6.2/clr/hipamd/include /opt/rocm/llvm/lib/cmake/llvm/../../..'
+ /opt/rocm/llvm/lib/cmake/llvm/../../../bin/clang -O3 --hip-path=/root/rocm/ROCm-6.2/clr/build/hipamd/include/.. -std=c++17 -nogpulib -isystem /root/rocm/ROCm-6.2/clr/build/hipamd/include -isystem ../HIP/include -isystem /root/rocm/ROCm-6.2/clr/hipamd/include --cuda-device-only --cuda-gpu-arch=gfx1030 -x hip /tmp/hip_pch.4047291/hip_pch.h -E
/tmp/hip_pch.4047291/hip_pch.h:1:10: fatal error: 'hip/hip_runtime.h' file not found
    1 | #include "hip/hip_runtime.h"
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx1030.
CMake Error at hipamd/src/CMakeLists.txt:200 (message):
  Failed to embed PCH


-- Configuring incomplete, errors occurred!
